image: docker:latest

variables:
  BUILD_DATE: "`date +%Y-%m-%dT%H:%M:%SZ`"
  PIPELINE_ID: "$CI_PIPELINE_ID"
  VCS_REF: "$CI_COMMIT_SHA"

services:
- docker:dind

before_script:
- docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
- git submodule init
- git submodule update

build:
  stage: build
  script:
  - docker build --pull --build-arg BUILD_DATE="${BUILD_DATE}" --build-arg PIPELINE_ID="${PIPELINE_ID}" --build-arg VCS_REF="${VCS_REF}" -t $CI_REGISTRY_IMAGE .
  - docker tag $CI_REGISTRY_IMAGE $CI_REGISTRY_IMAGE:develop
  - docker push $CI_REGISTRY_IMAGE:develop
  only:
  - develop

build-latest:
  stage: build
  script:
  - docker build --pull --build-arg BUILD_DATE="${BUILD_DATE}" --build-arg PIPELINE_ID="${PIPELINE_ID}" --build-arg VCS_REF="${VCS_REF}" -t $CI_REGISTRY_IMAGE .
  - docker push $CI_REGISTRY_IMAGE
  only:
  - master